# Generated by Django 4.1.1 on 2023-07-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_remove_laboratorio_director_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'ordering': ['nombre']},
        ),
    ]
