# Generated by Django 4.1.1 on 2023-07-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_directorgeneral_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['nombre']},
        ),
    ]
